app/home/forms.py
# !/user/bin/env/python
# -*- coding:utf-8 -*-
# Author: qixuanye
# Time: 2019/12/09

from flask_wtf import FlaskForm
from wtforms import SelectField, TextAreaField, SubmitField
from wtforms.validators import DataRequired
from app.models import Function_list

'''
查询表单
'''
class query_form(FlaskForm):
    function_type = SelectField(
        label = "功能点分类",
        description = "功能点分类",
        validators = [
            DataRequired("分类不能为空！")
        ],
        choices = [(v.func_id, v.func_name) for v in Function_list.query.filter_by(is_del = 0)],
        default = 1,
        coerce = int,
        render_kw = {
            "class": "form-control boxClear",
            # "style": "width:600px"
        }
    )
    content = TextAreaField(
        label = "查询内容",
        description = "查询内容",
        validators = [
            DataRequired("查询内容不能为空！")
        ],
        render_kw = {
            "class": "form-control boxClear",
            # "style": "height: 150px",
            # "style": "width: 800px",
            "id": "content"
        }
    )
    submit = SubmitField(
        "问题查询",
        render_kw = {
            "class": "btn btn-primary"
        }
    )

app/home/__init__.py
# !/user/bin/env/python
# -*- coding:utf-8 -*-
# Author: qixuanye
# Time: 2019/11/14 14:25

from flask import Blueprint

home = Blueprint("home", __name__)


import app.home.views

app/home/views.py
# !/user/bin/env/python
# -*- coding:utf-8 -*-
# Author: qixuanye
# Time: 2019/11/14 14:25

# 导入该模块中蓝图对象home
from . import home
from flask import render_template, redirect, request, session, url_for
from .forms import query_form
from app.models import Function_list, Question_base, Answer_base, Func_ques_relation, Search_log, db, Temp, Keyword_bus, \
    Answer_log
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor
# 调用百度SDK
from aip import AipNlp
import requests, json, time, threading

URL = "https://aip.baidubce.com/rpc/2.0/nlp/v2/simnet"
ACCESS_TOKEN = '24.39643d723879576481b053c4f67e9c6c.2592000.1581593348.282335-17973538'
# 百度SDK所需参数
APP_ID = '17973538'
API_KEY = 'yZjSKKtG1N5yudQg3Zml9MEh'
SECRET_KEY = 'LAPBsxEXpPHAoX4D3QUUbc2Q86NGSnG7'


# 查询路由
@home.route("/query", methods = ["GET", "POST"])
def query():
    form = query_form()
    if request.method == "GET":
        form.function_type.choices = [(v.func_id, v.func_name) for v in Function_list.query.filter_by(is_del = 0)]
    if form.validate_on_submit():
        data = form.data
        search_record = Search_log(
            func_id = data["function_type"],
            search_text = data["content"],
            ques_sort = 1,
            create_time = datetime.now()
        )
        db.session.add(search_record)
        db.session.commit()
        return redirect(
            url_for('home.query_list', page = 1, type = data["function_type"], content = search_record.search_text))

    return render_template("home/query.html", form = form)

# 查询列表
@home.route("/query/list", methods = ["GET", "POST"])
def query_list():
    # 获取url中的参数值
    page = int(request.args.get("page"))
    type = int(request.args.get("type"))
    content = request.args.get("content")
    # 获取查询分类下的问题信息
    question_datas = Func_ques_relation.query.filter_by(func_id = type, is_del = 0).all()
    # 设置线程池
    threadPool = ThreadPoolExecutor(max_workers = 10)
    ques_id_score = {}
    # 多线程返回结果
    for v in question_datas:
        future1 = threadPool.submit(text_compare, content, v.ques_title, v.ques_id)
        def text(future):
            (ques_id, score) = future.result()
            ques_id_score[ques_id] = score
        future1.add_done_callback(text)
        # score1 = text_compare_sdk(content, v.ques_title)
        # ques_id_score[v.ques_id] = text()
    threadPool.shutdown(wait = True)
    print(ques_id_score)
    # 对查询结果排序成倒序
    ques_id_sort = sorted(ques_id_score.items(), key = lambda ques_id_score: ques_id_score[1], reverse = True)

    for v in ques_id_sort:
        query_item = Question_base.query.join(
            Func_ques_relation
            # join(Keyword_bus).
        ).filter(
            Question_base.ques_id == v[0],
            Question_base.is_del == 0,
            Func_ques_relation.is_del == 0
        ).first()
        temp = Temp(
            ques_id = query_item.ques_id,
            ques_title = query_item.ques_title,
            func_type = query_item.func_ques_relations[0].func_id,
            func_name = query_item.func_ques_relations[0].func_name,
            create_time = datetime.now()
        )
        db.session.add(temp)
    db.session.commit()

    page_data = Temp.query.paginate(page = int(page), per_page = 10)

    delete_data = Temp.query.all()
    for m in delete_data:
        db.session.delete(m)
    db.session.commit()
    return render_template("home/query_list.html", title = "查询列表",
                           page_data = page_data, func_type = type, content_text = content)


# 问题详情
@home.route("query/data/<id>", methods = ["GET"])
def question_content(id):
    question = Question_base.query.get_or_404(int(id))
    # 根据id获取func_ques_relation的信息
    function_type = Func_ques_relation.query.filter_by(ques_id = int(id), is_del = 0).first()
    # 根据id获取answer_base的信息
    answer = Answer_base.query.filter_by(ques_id = int(id), is_del = 0).first()
    # 根据id获取业务关键字
    bus_keys = Keyword_bus.query.filter_by(ques_id = int(id), is_del = 0)
    # 对业务关键字进行拼接
    bus_key_text = ""
    for v in bus_keys:
        bus_key_text = bus_key_text + v.keyword_bus_name + ';'
    bus_key_text = bus_key_text[:-1]
    # 将访问记录放入answer_log中
    answer_log = Answer_log(
        ques_id = question.ques_id,
        # 0-无用，1-有用，2-无记录，3-功能没做完
        is_useful = 3,
        search_text = "这是一个测试",
        create_time = datetime.now(),
        is_del = 0
    )
    db.session.add(answer_log)
    db.session.commit()
    return render_template("home/question_content.html", title = "问题详情", question_data = question,
                           function_data = function_type, answer_data = answer, bus_key = bus_key_text)


# @home.route("/test", methods = ["GET", "POST"])
def test():
    text1 = "需求单位找不到该组织，但是可以再月度产值找到"
    text2 = "在工程信息里新增了项目，编制申购计划时，新增的项目不出来"
    response = text_compare(text1, text2)
    print(response)
    return "test"


# 利用百度api获取短文本比较结果,返回最终比较的值
def text_compare(text1, text2, ques_id):
    params = {'access_token': ACCESS_TOKEN,
              'charset': 'UTF-8'}
    headers = {'Content-Type': 'application/json'}
    # text1 = text[0]
    # text2 = text[1]
    body = {"text_1": text1,
            "text_2": text2}
    response = requests.post(URL, json = body, headers = headers, params = params)
    res_dict = json.loads(response.text)
    print(res_dict['score'])
    return ques_id, float(res_dict['score'])

# 利用百度SDK获取短文本比较结果
def text_compare_sdk(text1, text2, ques_id):
    a = 1
    client = AipNlp(APP_ID, API_KEY, SECRET_KEY)
    result = client.simnet(text1, text2)
    score = float(result["score"])
    print(score)
    return ques_id, score

app/templates/home/layout.html
<!--
Author: qixuanye
Time: 2019/12/09
-->

<!doctype html>

<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- 链接bootstrap的css文件-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/bootstrap.min.css')}}">
    <title>鲁班智能答疑系统</title>
    <style>
        .clear{background-color: rgba(255, 255, 255, 0.95) !important;box-shadow: none;border:none;}
        .pageClear{opacity:0.7}
        .navClear{opacity: 0.7}
    </style>
    {% block css %}{% endblock %}

</head>

<body background="{{ url_for('static', filename = 'image/2企业愿景.jpg')}}" style=" background-repeat:no-repeat ;
background-size:100% 100%;
background-attachment: fixed;">
<nav class="navbar navber-light navClear" style="background-color: #e3f2fd">
    <div class="container">
        <a class="navbar-brand"> </a>
        <a class="btn btn-outline-danger" href="/home/query">返回继续查询</a>
    </div>
</nav>
<div class="col-md-8 offset-md-2" ` style="margin-top:60px">
    <div class="card clear">
        <div class="card-header"><strong>{{ title }}</strong></div>
        <div class="card-body">
            {% block content%}{% endblock %}
        </div>
    </div>
</div>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{{ url_for('static', filename='js/jquery.slim.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/page.html
<!--
Author: qixuanye
Time: 2019/12/05
-->

{% macro page(data, func_type, content_text, url) %}
{% if data %}
<nav>
    <ul class="pagination">
        {% if data.has_prev %}
        <li class="page-item"><a class="page-link pageClear"
                                 href="{{ url_for(url,page=data.prev_num,type=func_type,content=content_text) }}">上一页</a>
        </li>
        {% else %}
        <li class="page-item disabled"><a class="page-link pageClear">上一页</a></li>
        {% endif %}

        {% for v in data.iter_pages() %}
        {% if v %}
        {% if v != data.page %}
        <li class="page-item"><a class="page-link pageClear" href="{{ url_for(url,page=v,type=func_type,content=content_text) }}">{{ v
            }}</a></li>
        {% else %}
        <li class="page-item active"><a class="page-link pageClear" href="{{ url_for(url,page=v,type=func_type,content=content_text) }}">{{
            v }}</a></li>
        {% endif %}
        {% endif %}
        {% endfor %}

        {% if data.has_next %}
        <li class="page-item"><a class="page-link pageClear"
                                 href="{{ url_for(url,page=data.next_num,type=func_type,content=content_text)}}">下一页</a></li>
        {% else %}
        <li class="page-item disabled"><a class="page-link pageClear">下一页</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endmacro %}

app/templates/home/query.html
<!--
Author: qixuanye
Time: 2019/12/09
-->
{% extends "home/query_layout.html" %}
{% block css %}
<style>
    .boxClear{background-color: rgba(255, 255, 255, 0.95) !important;box-shadow: none;border:none;}
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12" style="margin-top: 30px;">
            <h2 class="text-center"><strong>鲁班智能答疑系统</strong></h2>
            <form method="post" enctype="multipart/form-data" style="margin-top: 30px" class="col-md-8 offset-md-2">
                <div class="form-group">
                    <label><strong>功能点分类</strong></label>
                    {{ form.function_type }}
                    {% for v in form.function_type.errors %}
                    <p style="color: red">{{ v }}</p>
                    {% endfor %}
                </div>
                <div class="form-group">
                    <label><strong>查询问题内容</strong></label>
                    <br>
                    {{ form.content }}
                    {% for v in form.content.errors %}
                    <p style="color: red">{{ v }}</p>
                    {% endfor %}
                </div>
                {{ form.submit }}
                {{ form.csrf_token }}
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/query_layout.html
<!--
Author: qixuanye
Time: 2019/12/09
-->

<!doctype html>

<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- 链接bootstrap的css文件-->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/bootstrap.min.css')}}">
    <title>鲁班智能答疑系统</title>
    {% block css %}{% endblock %}
    <style>
        #clear{background-color: rgba(255, 255, 255, 0) !important;box-shadow: none;border:none;}
    </style>
</head>

<body background="{{ url_for('static', filename = 'image/7责任理念.jpg')}}" style=" background-repeat:no-repeat ;
background-size:100% 100%;
background-attachment: fixed;">

<div class="col-md-8 offset-md-2"  style="margin-top:90px">
    <div class="card" id="clear">
        <div class="card-header">{{ title }}</div>
        <div class="card-body">
            {% block content%}{% endblock %}
        </div>
    </div>
</div>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="{{ url_for('static', filename='js/jquery.slim.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% block js %}{% endblock %}
</body>
</html>

app/templates/home/query_list.html
<!--
Author: qixuanye
Time: 2019/12/09
-->
{% extends "home/layout.html" %}
{% import "home/page.html" as pg %}
{% block css %}
<style xmlns="http://www.w3.org/1999/html">
    .table td, .table th{
        vertical-align: middle;
    }


</style>
{% endblock %}


{% block content %}
<script type="text/javascript">
    function removeClassType($this) {
        $($this).attr("title",$this.innerText);
    }


</script>
<style>
    table { table-layout:fixed;}
    .award-name{-o-text-overflow:ellipsis;text-overflow:ellipsis;overflow:hidden;white-space:nowrap;
</style>
<table class="table table-bordered">
    <thead>
    <tr style="able-layout:fixed">
        <th style="width: 60%">问题标题</th>
        <th style="width: 25%">功能点分类</th>
        <th style="width: 15%">查看回答</th>
    </tr>
    </thead>
    {% for v in page_data.items %}
    <tr style="font-size:12px">
        <td class="award-name" onmousemove="removeClassType(this)"><strong><font size="2.5">{{ v.ques_title }}</font></strong></td>
        <td class="award-name" onmousemove="removeClassType(this)"><strong><font size="2.5">{{ v.func_name }}</font></strong></td>
        <td>
            <a href="{{ url_for('home.question_content', id = v.ques_id) }}"
               class="btn btn-sm btn-info">查看</a>
        </td>
    </tr>
    {% endfor %}
</table>
<!-- 分页-->
{{ pg.page(page_data, func_type, content_text, 'home.query_list') }}

{% endblock %}

app/templates/home/question_content.html
<!--
Author: qixuanye
Time: 2019/12/12
-->
{% extends "home/layout.html" %}
{% block css %}
<!-- Latest compiled and minified CSS -->
<!--
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
-->
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename = 'css/bootstrap-select.min.css')}}">
<!-- Latest compiled and minified JavaScript -->
<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>
-->
<script type="text/javascript" charset="UTF-8"
        src="{{ url_for('static', filename = 'js/bootstrap-select.min.js') }}"></script>
<script type="text/javascript" charset="UTF-8"
        src="{{ url_for('static', filename = 'ue/ueditor.config.js') }}"></script>
<script type="text/javascript" charset="UTF-8" src="{{ url_for('static', filename = 'ue/ueditor.all.js') }}"></script>
<script type="text/javascript" charset="UTF-8"
        src="{{ url_for('static', filename = 'ue/lang/zh-cn/zh-cn.js') }}"></script>
{% endblock %}
{% block content %}
<form>
    <div class="form-group">
        <label>问题标题</label>
        <input type="text" class="form-control" disabled="disabled" value="{{ question_data.ques_title }}">
    </div>
    <div class="form-group">
        <label>功能点分类</label>
        <input type="text" class="form-control" disabled="disabled" value="{{ function_data.func_name }}">
    </div>
    <div class="form-group">
        <label>业务关键字（请用';'分隔）</label>
        <input type="text" class="form-control" disabled="disabled" value="{{ bus_key }}">
    </div>
    <div class="form-group">
        <label>回答</label>
        <textarea style="height: 300px" id="content">{{ answer_data.answer_text }}</textarea>
    </div>
</form>
{% endblock %}
{% block js %}
<script>
    var ue = UE.getEditor("content");
    $(document).ready(function () {
        $("#m1").addClass("active");
    });
</script>
{% endblock %}